services:
  nginx:
    container_name: ${CI_PROJECT_PATH_SLUG}-nginx  
    restart: always
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    environment:
      TZ: "Asia/Novosibirsk"
    volumes:
      - ${PROJ_DIR}:/var/www
    ports:
      - "${NGINX_HTTP_PORT}:80"
    networks:
      - internal

  php-fpm:
    container_name: ${CI_PROJECT_PATH_SLUG}-php-fpm 
    restart: always
    build:
      context: docker/php-fpm
    volumes:
      - ${PROJ_DIR}:/var/www
      - ${PROJ_DIR}/docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - internal

networks:
    internal:
      name: ${CI_PROJECT_PATH_SLUG}-net
